### ISSUE TITLE
No support for POST, PUT, DELETE?

### ISSUE THREAD

**Issue by eis** [wiibaker/robotframework-rest-java#1]
Library claims to be REST testing framework, but it seems it only supports testing JSON responses of GET requests. Apparently sending or changing anything is not supported. Is this correct?

**Comment by wiibaker** [comment]
Looks like to be so. The library was initially created to support our own needs, which then only had GET methods. Adding support for those others should not be too difficult task.

Probably requires an extra parameter added to the keywords to specify the method required. Also one problem might be in POST/PUT that you will need to pass the data somehow also.

I can add it in some near future or you can make the code changes too if you like so.

**Comment by eis** [comment]
It was easy enough to extend this library in the application itself, worked like a charm. However, I ended up changing the API like

```
POSTJsonContent  url   content
PUTJsonContent  url   content
Previous Response Json Should Match   jsonPath  useExactMatch
PUTChildContentToPreviousResponse   urlprefix  urlpostfix content
```

etc, which is not the nicest way. However doing url, method, content and response content all in same directive looked to be real messy. To implement these in the library itself would require some more planning. If I were to implement it now, I would introduce state and do it maybe like

```
ReadJsonContent   url/file/literal
PreviousJsonContentShouldMatch  jsonPath useExactMatch
POSTPreviousJsonContent  url 
PreviousJsonResponseShouldMatch  jsonPath useExactMatch
```

so things are splitted into separate directives. Also, there needs to be a way of getting an ID of a created resource and use it in the next request, but I don't know if Robot provides a way to do that out of the box.

**Comment by eis** [comment]
I also ended up adding optional printing of REST responses to stdout. It helped debugging quite a bit.

**Comment by wiibaker** [comment]
I also started to develop this a bit by adding option to specify the method and possibly also data and contenttype of the data as parameters to the keywords. You'd use it like

Json Should Be Equal     JSON/URI    JSON/URI    [True/False]    [GET/POST/PUT/DELETE]   [DATA]   [CONTENTTYPE]

It would default to GET method as it usually is I believe. How would you see that?

It might get a bit messy if you have a lot of POST/PUT/DELETE requests, but then you could wrap these into a custom keyword like "Post Json Should Be Equal" where you only give the json/url and data perhaps.

Also would you mind sharing your changes for me too look through?

**Comment by wiibaker** [comment]
I added the above described functionality in the new 0.3 version. Check it out. Any comments or feedback is appreciated.
